### ISSUE TITLE
Electricity bill

### ISSUE THREAD

**Issue by prateekthakur272** [tanu-chouhan/Java-Programs#2]
Create a class ElectricityBill with a constructor that calculates the amount generated by taking last_reading and current_reading as input

Create a method display that displays the generated bill in a beautiful format

Generated amount as

For first 100 units each unit cost rs 10.
For next 100 units each unit cost rs 8.
For remaining units each cost rs 5.

Class has following attributes 

billerName
lastReading
prevReading
totalUnits
bill

**Comment by tanu-chouhan** [comment]
done
